#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDsvyWrFH+h2+blJv72DWxMq80YvfBu2GjzCR7RJWoM5evfKptXHNCZxFZHXh0WNR+4f1yEZDu9BBMvHNyUXYnCN09nTxh2cib0sJ2RVTdbRHzcsxZ6Wji7CgZzKtTIh4hBtrd4K8A0/J5TIhVj2cethrA1QR+EmgGDEynAofBROcKNRfKbBF64Je7NmFFNksp6uU9jk5IhV8Gt0RZAWuVfhAkcTtp/lngY3+saLZNM0CX5tE6mpYfeiT5UE1grXqPa7q5pv1eabfxkRX4+8NzpnzxYnURrfL2AHsa0SPOIy+UDmiIOFo+I1fJdsYEfd82XLki7h1YaBbH0IL2+Y191tOmWB4v0aDNvuSvS0lBfLC/eCWLZfiyjXOpKcy8OtZ6HhrCmbC510lyz/Eg4IPoDokpJpOcy1DecmMTs/FwdH0D4t12NBiOxnGcmfL+Y1vnto/tRVTMqoaBdwGgmta1CU70cdLBBsbILgTwxra9fLW18FA43D8X6dHTIdbNqTt9qKnc34BjnD9nx9mNaljWE1fr00I103+E6Ig/d5853rmRXEgw9cbyAnW9GEmImiXPMEVNX0qETQCem21esxlQlifszfkQra0tD5hcuhvDZ1x+gZ0XUJN7HlpxAK9kPbsO7JaKYn81DkF8uh8urfszJuH4BjlpOqpv0KMJusArDWQ== core
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBeYLFEduQnXslKcgO+Dq1vC0lT2feBleV2H88FAe0fU89VTH4P8i6ujlrvdsyPWaAF84G1rseiWVadMimj7/A6XJOXB78sfd/8s7C77QY1N6SgtkgSTJDybZ2QW65xgK25ZG3fvUUf/9rNsWo7Of/kvY6f+I1LWkZ9zl68/oj80ZibSnB6TsIOgL6MY2yE99Dq9r7V/xBKD/U/MPJBVYtyKiOxvsKhtk9jDD/ReuzwjGb6GK6D4enJ264oiB7oZfHdXamao9g3Zn7EDvna7fvKeA6l4AfannsIwvZeGb0vpij4UoYdjCz/PNJtkMyPekyrlDH8jpFkSR6OGdNGubvLtB31WnPIsdddHTsHmlP9im7ceUnSKayyaLcxs8F1vcwlbVW73duSUNBWH0tQJQKylgKXxaQJdKLzvgGMVYvMJBg8ed6OQHzqOcc3tN53+YgjJpy/pckPdYATtbdtKKBapC3HKh7UmLXSfFGzGQmwCGdPHN3/dr9xIYZ9zVH+FmMyQ1iwHmyt3zQ+EOyTHWXTcQ4C+X5LGXBlzNR4YM+kDX6JdRdYYLHFCaL171pUtvV3ayNRW2WFeRFKgiY7zdc5b2/TiokuoBSODzHfn6jO5MIzOqJDjt5jq7WYAGcD2qFx/oUFy5p0Lzs5ijyCNx0FHkxi2O8pJJcDoyWpploSQ== mac

# Users
users:
  - name: keita
    passwd: 1d1aafa85f2b8e5bc8bfd06085da85557072b10d1de57dcfbe30736556b1d0af
    groups:
      - sudo
      - docker
 
 # include one or more SSH public keys
